    version: '3.8'

    services:
        elasticsearch:
                    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.28
                    container_name: elasticsearch
                    environment:
                        - node.name=elasticsearch
                        - cluster.initial_master_nodes=elasticsearch
                        - bootstrap.memory_lock=true
                        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
                        # - "ELASTIC_PASSWORD=bazinga"
                        # - xpack.security.enabled=false
                        # - xpack.security.transport.ssl.enabled=false
                        # - xpack.security.http.ssl.enabled=false 
                    ulimits:    
                        memlock:
                             soft: -1
                             hard: -1
                    volumes:
                        - /mnt/f/elasticsearch/elasticsearch/data:/usr/share/elasticsearch/data
                        
                    ports:
                        - 9200:9200
        kibana:
            image: docker.elastic.co/kibana/kibana:7.17.28
            container_name: kibana
            ports:
                - 5601:5601
            environment:
                - ELASTICSEARCH_URL=http://elasticsearch:9200
                - ELASTICSEARCH_HOSTS="http://elasticsearch:9200"
               # - ELASTICSEARCH_USERNAME=elastic
               #  - ELASTICSEARCH_PASSWORD=bazinga    
               
            
            depends_on:
                - elasticsearch
        nginx:
            image: pablo/tarsbikecraft
            container_name: tarsbikecraft
            ports:
               - 8080:80
           
            